### ISSUE TITLE
add in: @shannakurpe checklist

### ISSUE THREAD

**Issue by evanwolf** [evanwolf/site-retirement-checklist#1]
http://blog.hubspot.com/marketing/website-launch-checklist 
## Page Content

First, take some time to review all of the content on your website with a fine-tooth comb. Of course, that means page content, but don't forget about your premium content too. From data-driven content and downloadable documents to rich media such as videos and images, you want to make sure everything is in place, working properly, and looking beautiful.

So my suggestion is to check the following items once -- and then check them again. You really don't want to miss a single typo or grammatical error.
- [ ] Web copywriting has been proofread. Spelling and grammar are correct.
- [ ] Paragraphs, headers, lists, and other formatting are correct.
- [ ] Copyright date (perhaps in the footer) includes the current year.
- [ ] Company contact details are accurate throughout the website.
- [ ] Generic content, such as lorem ipsum, has been properly removed and replaced.
- [ ] Images are in the correct places, formatted and working on all devices.
- [ ] Videos are in the correct places, formatted and working on all devices.
- [ ] Audio files are in the correct places, formatted and working on all devices.
- [ ] All premium content, such as case studies, ebooks, and whitepapers, have been proofread. Spelling and grammar are correct.
- [ ] All premium content, such as case studies, ebooks, and whitepapers, are stored in their proper libraries/databases and work properly.
- [ ] Rights to images, fonts, and other content have been properly licensed and/or cited.
## Design

Second, take the necessary steps to ensure that the site design is pixel perfect. If you have a responsive website (and you definitely should), you need to check the design across all devices. Your site should be looking good not just on an office desktop, but also on laptops, tablets, and mobile phones.
- [ ] Website pages are compatible across browsers (IE 7 8, 9 and 10, Firefox, Chrome, Safari).
- [ ] Website pages are compatible across devices (Android, iPhone, tablets).
- [ ] CSS/HTML is properly validated.
- [ ] Scripts are optimized across web pages.
- [ ] Images are optimized across web pages.
- [ ] CSS is optimized across web pages.
- [ ] Favicon is in place and rendering properly.
- [ ] Paragraph styles are working properly (headers, lists, block quotes).
## Functionality

Third, take some time to test and validate all of the different features on your website. Lead generation forms, social sharing, CRM integration, and any other technology should work flawlessly across your website.
- [ ] Forms are submitting data properly.
- [ ] Thank-you message or page displays after form is submitted.
- [ ] Form data is being emailed to a recipient and/or stored in a company database.
- [ ] Auto-responders are working properly (if applicable).
- [ ] Internal links across web pages are working properly.
- [ ] External links across web pages are working properly, and open in a new tab.
- [ ] Social media share icons are working properly.
- [ ] Feeds are working properly (RSS, news, social media).
- [ ] Company logo is linked to the homepage.
- [ ] Load time for site pages is optimized.
- [ ] 404 Redirect pages are in place (page-not-found.aspx).
- [ ] Integrations with third-party tools, such as your CRM, e-commerce software, and/or marketing platform, are running smoothly.
## SEO

Fourth, take some time to ensure that your website has been given a solid foundation for SEO success. From site architecture and content hierarchy to metadata and XML sitemaps, do not leave any stone unturned.
- [ ] Pages have unique page titles (fewer than 70 characters, includes keywords).
- [ ] Pages have unique meta descriptions (fewer than 156 characters, includes keywords).
- [ ] Pages have keywords (fewer than 10, all words appear in page copy).
- [ ] Metadata is properly in place for any content in an RSS feed.
- [ ] Metadata is properly in place for any social media sharing content.
- [ ] Spelling and grammar are correct in all metadata.
- [ ] Alt tags have been added to every image.
- [ ] A dynamic XML sitemap has been created.
- [ ] The XML sitemap has been submitted to search engines.
- [ ] Page URLs consistently reflect site information architecture.
- [ ] 301 redirects are in place for all old URLs (redirecting old to new pages).
- [ ] rel="nofollow” tags are in place on applicable links and pages.
## Analytics

Fifth, make sure your website is set up to capture web data and analytics. This valuable information will allow you to continually improve your website going forward, so you don't want to forget this stuff.
- [ ] Your website analytics codes have been inserted on website.
- [ ] Relevant IP addresses have been excluded from analytics tracking.
- [ ] Funnels and goals have been properly created in your analytics software (if applicable).
- [ ] Google Webmaster and Google Analytics accounts have been properly synced.
- [ ] Google AdWords and Google Analytics accounts have been properly synced (if applicable).
## Security & Backups

Sixth, you can prevent loss of data and protect against malware and other damages by properly setting up site security and regular backups.
- [ ] 24/7 monitoring scripts are installed.
- [ ] A copy of the final website has been made for backup purposes.
- [ ] Ongoing copies of the website are being created and stored on a regular basis.
- [ ] Passwords and other website credentials are stored in a secure database.
## Compliance

Finally, make sure your website complies with any applicable laws and regulations. Internet law can be sticky, and each industry has its own set of rules to follow. So it's best to consult with your legal counsel to make sure you aren't missing anything -- this post is not legal guidance. Here are a few you might need to know about:
- [ ] Web pages offer accessibility for users with disabilities (WAI-ARIA).
- [ ] Web pages announce if the website uses cookies (required in some countries).
- [ ] Website is compliant with usage rights for purchased or borrowed code, images, and fonts.
- [ ] Terms and privacy policies are visible to website visitors.
- [ ] Website is PCI compliant (if you’re storing and processing credit cards).
